[project]
name = "tpflow"
description = ""
readme = "README.md"
requires-python = ">=3.11"
version = "0.1.0"

dependencies = [
  "numpy",
  "jax",
  "h5py",
  "matplotlib",
  "hydra-core",
  "hydra-submitit-launcher",
  "humanize",
  "pandas",
  "seaborn",
  "wandb[media] (>=0.24.2,<0.25.0)",
  "zarr (>=3.1.5,<4.0.0)",
  "rich (>=14.3.2,<15.0.0)",
  "typer (>=0.21.1,<0.22.0)",
  "hdfv @ git+ssh://git@github.com/Algopaul/hdfv.git",
  "flanch @ git+ssh://git@github.com/Algopaul/flanch.git",
]

[project.optional-dependencies]
dev = [
  "pylint>=2.6.0",
  "yapf",
  "pytest",
  "isort",
]

[tool.setuptools]
packages = ["tpflow"]
